version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: words-englishes
    environment:
      POSTGRES_DB: words-englishes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: